config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "top_pages#top"
  resources :maps
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def new; end
end

app/controllers/top_pages_controller.rb
class TopPagesController < ApplicationController
  def top; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PanStroll</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maps/new.html.erb
<head>
  <title>Maps and Places Autocomplete</title>
  <script>
    async function init() {
      await customElements.whenDefined('gmp-map');

      const map = document.querySelector('gmp-map');
      const marker = document.querySelector('gmp-advanced-marker');
      const placePicker = document.querySelector('gmpx-place-picker');
      const infowindow = new google.maps.InfoWindow();

      map.innerMap.setOptions({
        mapTypeControl: false
      });

      placePicker.addEventListener('gmpx-placechange', () => {
        const place = placePicker.value;

        if (!place.location) {
          window.alert(
            "No details available for input: '" + place.name + "'"
          );
          infowindow.close();
          marker.position = null;
          return;
        }

        if (place.viewport) {
          map.innerMap.fitBounds(place.viewport);
        } else {
          map.center = place.location;
          map.zoom = 10;
        }

        marker.position = place.location;
        infowindow.setContent(
          `<strong>${place.displayName}</strong><br>
            <span>${place.formattedAddress}</span>
        `);
        infowindow.open(map.innerMap, marker);
      });
    }

    document.addEventListener('DOMContentLoaded', init);
  </script>
  <script type="module" src="https://unpkg.com/@googlemaps/extended-component-library@0.6">
  </script>
  <style>
    html,
    body {
      height: 92%;
      margin: 0;
      padding: 0;
    }

    .place-picker-container {
      padding: 20px;
    }
  </style>
</head>
<body>
  <gmpx-api-loader key=<%= ENV["GOOGLE_API_KEY"] %> solution-channel="GMP_GE_mapsandplacesautocomplete_v1">
  </gmpx-api-loader>
  <gmp-map center="35.6809591,139.7673068" zoom="13" map-id="DEMO_MAP_ID">
    <div slot="control-block-start-inline-start" class="place-picker-container">
      <gmpx-place-picker placeholder="パン屋さんを検索!" id="bled-search" ></gmpx-place-picker>
    </div>
    <gmp-advanced-marker></gmp-advanced-marker>
  </gmp-map>
</body>

app/views/top_pages/top.html.erb
<title>Top Page</title>
<div class="flex flex-col mx-auto top-wrapper">
  <h1 class="text-5xl font-bold text-center pt-20 mt-20">パン Stroll</h1>
  <p class="text-lg text-center mt-4">パンと一緒に、街を楽しもう</p>
  <%= link_to 'パン屋を調べる', new_map_path , class: "text-5xl font-bold text-center pt-20 mt-20"%>
</div>